### ISSUE TITLE
Set up IntelliJ to be in sync with repo

### ISSUE THREAD

**Issue by Jermon1** [Calixte-Williams/set08803_gw#15]
Do a successful pull with IntelliJ so everyone has the repo

**Comment by Calixte-Williams** [comment]
Got an error while building the app:

`
Step 2/4 : COPY ./target/set08803_gw-0.1.0.1-jar-with-dependencies.jar /tmp
Error response from daemon: COPY failed: file not found in build context or excluded by .dockerignore: stat target/set08803_gw-0.1.0.1-jar-with-dependencies.jar: file does not exist
Failed to deploy '<unknown> Dockerfile: Dockerfile': Can't retrieve image ID from build stream
`

**Comment by Calixte-Williams** [comment]
This has been completed as all team members have successfully clones this repository to your local machines and they were able to run the app locally.

The error in my above comment was due to incorrect building of the docker containers from the repo on my own part. Works well now!

**Comment by ShahidiLeonce** [comment]
GitHub Repo was pulled and launched the app successfully from IntelliJ locally.

**Comment by Jermon1** [comment]
Repo was pulled and could be worked on locally and pushed

**Comment by Desiree98** [comment]
Repo was pulled and could be worked on locally and pushed

**Comment by Terrel-Deligny** [comment]
GitHub Repo was pulled and launched successfully from IntelliJ and runs locally
