### ISSUE TITLE
As an employee, I want to access a list of all countries in the world sorted by largest population to smallest so that I can use the information for data entry purposes.

### ISSUE THREAD

**Issue by Desiree98** [Calixte-Williams/set08803_gw#25]

**Comment by Jermon1** [comment]
Edit title to include smallest from largest to match report 1:

All the countries in the world organised by largest population to smallest.

**Comment by Calixte-Williams** [comment]
Testing phase of this feature. Database connects and successfully return print out of line line result.
Features to be added next:
- Iterate over all entries in the World table and display a completed report
- Separate code to get the information from World Database and code to display/print information from World Database
