### ISSUE TITLE
As a coordinator, I want to compile reports on the top N populated countries in a region where N is provided by the user to facilitate coordination of international projects and initiatives.

### ISSUE THREAD

**Issue by Desiree98** [Calixte-Williams/set08803_gw#34]

**Comment by Jermon1** [comment]
Looks good - works for report 6

The top N populated countries in a region where N is provided by the user.

**Comment by Jermon1** [comment]
![image](https://github.com/Calixte-Williams/set08803_gw/assets/123422184/6c1fd891-7496-4b29-abf1-495bc82def4c)
done
