### ISSUE TITLE
As a data analyst, I want to generate reports of  all the countries in a region organised by largest population to smallest to identify demographic patterns and correlations.

### ISSUE THREAD

**Issue by Desiree98** [Calixte-Williams/set08803_gw#40]

**Comment by Jermon1** [comment]
Changed to match report # 3
 All the countries in a region organised by largest population to smallest

**Comment by Jermon1** [comment]
![image](https://github.com/Calixte-Williams/set08803_gw/assets/123422184/f2c70c06-5d9b-490a-92d6-9bac5ed2dc4b)
