### ISSUE TITLE
As a marketing manager, I want to generate a report of the countries in a continent organised by largest population to smallest to identify new market opportunities and develop innovative marketing strategies.

### ISSUE THREAD

**Issue by Desiree98** [Calixte-Williams/set08803_gw#59]

**Comment by Jermon1** [comment]
Changed title to match report # 2
All the countries in a continent organised by largest population to smallest

**Comment by Jermon1** [comment]
![image](https://github.com/Calixte-Williams/set08803_gw/assets/123422184/677718b1-9b00-4ea1-b8ef-2e5f16f21f3e)

Generates report of countries from largest pop. to smallest pop.
