### ISSUE TITLE
Install Graphviz

### ISSUE THREAD

**Issue by Calixte-Williams** [Calixte-Williams/set08803_gw#65]
Install Graphviz on all member computers to properly view UML diagrams in Use-Cases. It will integrate with IntelliJ upon install.
https://www.graphviz.org/download/

**Comment by Jermon1** [comment]
installed

**Comment by ShahidiLeonce** [comment]
Graphviz has been installed

**Comment by Terrel-Deligny** [comment]
Installed

**Comment by Desiree98** [comment]
Installed
